### ISSUE TITLE
Top title causes error

### ISSUE THREAD

**Issue by georgetasioulis** [deajan/traceroute_history#1]
Hello,

In the default smokeping config, there's a top menu/title:
```
menu = Top
title = Network Latency Grapher
remark = Welcome to the SmokePing website of xxx Company. \
         Here you will learn all about the latency of our network.
```

Because there's no `host` entry there, the following check will fail, giving an error:
```
ERROR :: Cannot parse smokeping config file. We need as much titles as host entries.
```
https://github.com/deajan/traceroute_history/blob/030c5fd3d66e2ad15dd37317fad5970051c491e7/config_management.py#L95-L97

**Comment by deajan** [comment]
Sorry, I didn't commit on this prioject for way too long.
I'll have it fixed soon.

**Comment by deajan** [comment]
Fixed in https://github.com/deajan/traceroute_history/commit/e3ce0eb58bbb573108dbb5543d48d4659967c0ae
