### ISSUE TITLE
unable to start Traceroute History Web UI Server

### ISSUE THREAD

**Issue by bogdanrotariu** [deajan/traceroute_history#7]
Hi there,

I am testing your project in Ubuntu 18.04 with Python 3.6 and when starting the ui server I get the error below, got any clue?

`May  5 14:47:45 infra systemd[1]: Started Traceroute History Web UI Server.
May  5 14:47:47 infra python3[46758]: 2022-05-05 14:47:47,753 :: INFO :: Running with database: /opt/traceroute_history/sqltest.db.
May  5 14:47:47 infra python3[46758]: INFO:     Will watch for changes in these directories: ['/opt/traceroute_history']
May  5 14:47:47 infra python3[46758]: 2022-05-05 14:47:47,840 :: INFO :: Will watch for changes in these directories: ['/opt/traceroute_history']
May  5 14:47:47 infra python3[46758]: INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
May  5 14:47:47 infra python3[46758]: 2022-05-05 14:47:47,841 :: INFO :: Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
May  5 14:47:47 infra python3[46758]: INFO:     Started reloader process [46758] using statreload
May  5 14:47:47 infra python3[46758]: 2022-05-05 14:47:47,841 :: INFO :: Started reloader process [46758] using statreload
May  5 14:47:49 infra python3[46758]: 2022-05-05 14:47:49,494 :: INFO :: Running with database: /opt/traceroute_history/sqltest.db.
May  5 14:47:49 infra python3[46758]: Process SpawnProcess-1:
May  5 14:47:49 infra python3[46758]: Traceback (most recent call last):
May  5 14:47:49 infra python3[46758]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
May  5 14:47:49 infra python3[46758]:     self.run()
May  5 14:47:49 infra python3[46758]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
May  5 14:47:49 infra python3[46758]:     self._target(*self._args, **self._kwargs)
May  5 14:47:49 infra python3[46758]:   File "/usr/local/lib/python3.6/dist-packages/uvicorn/subprocess.py", line 76, in subprocess_started
May  5 14:47:49 infra python3[46758]:     target(sockets=sockets)
May  5 14:47:49 infra python3[46758]:   File "/usr/local/lib/python3.6/dist-packages/uvicorn/server.py", line 67, in run
May  5 14:47:49 infra python3[46758]:     return asyncio.run(self.serve(sockets=sockets))
May  5 14:47:49 infra python3[46758]: AttributeError: module 'asyncio' has no attribute 'run'
`

**Comment by bogdanrotariu** [comment]
A newer pip fixed the issue.

**Comment by deajan** [comment]
Thanks for reporting back ;=)
